# Change these first
owner: ilger06 # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: PRC_ILGER
    url: $PRC_ILGER
  - name: ACIS_MOM01
    url: $ACIS_MOM01

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  name: ilger
  logoUrl: https://www.ilger.com/wp-content/uploads/2021/11/ILGER-logo.png
  baseUrl: /Uptime
  icon: https://www.ilger.com/wp-content/uploads/2022/03/ilger-logo-favicon.png
  introTitle: "Page - 7"
  introMessage: Servers Status with **real-time** data


  navbar:
    - title: Page1
      href: https://ilger00.github.io/Uptime/
    - title: Page2
      href: https://ilger01.github.io/Uptime/
    - title: Page3
      href: https://ilger02.github.io/Uptime/
    - title: Page4
      href: https://ilger03.github.io/Uptime/
    - title: Page5
      href: https://ilger04.github.io/Uptime/
    - title: Page6
      href: https://ilger05.github.io/Uptime/  
    - title: Page7
      href: /Uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

